name: Test

on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches: [main]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Formatting check
        run: deno task fmt-check

      - name: Lint check
        run: deno task lint

      - name: Test
        run: deno task test
